title: MAF 105
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/maf105
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Cronograma
   url: /cronograma
 - title: Contato
   url: /contato

social:
   github: maf105
   twitter: 
   facebook: 
   email: ufv.florestal.maf105@gmail.com

google_analytics: "UA-58263416-1"
